### ISSUE TITLE
Can I unwrap iterations?

### ISSUE THREAD

**Issue by JonathanWilbur** [hoxxep/rand-unique#3]
Thanks for making this great crate. I have needed something like this in many languages over a long career.

I think I can infer that this is the case, but, say you are iterating over unique `u8`s. What happens when you request the 257th `u8`? I presume you just get `None` and have to create a new random sequence.

**Comment by JonathanWilbur** [comment]
Sorry to spam you, but I just realized that `next()` returns a `T`, not an `Option<T>`. So now my question is: does it repeat after N+1 iterations? What happens when you run out of numbers that fit in `T`?

**Comment by hoxxep** [comment]
Hey, thanks for appreciating it!

Yes the sequence cycles on N+1. On the 257th call to `RandomSequence::<u8>::next()`, the index will do wrapped addition and would be the equivalent to index 0. The u8 sequence will cycle for every 256 elements, whether calling `next()` directory, or using `Iterator::next()`.

I can document this more clearly. Do you have a strong preference for avoiding the cycle and terminating the iterator?

**Comment by JonathanWilbur** [comment]
In my opinion, if the selling point of this library is to ensure unique IDs, I think the `RandomSequence` should be an actual [`ExactSizeIterator`](https://doc.rust-lang.org/std/iter/trait.ExactSizeIterator.html), and return a `None` after the last unique item. I think it makes it more explicit and effectively requires the user to handle the exhaustion of unique identifiers.

On the other hand, it is somewhat unwieldy to have to create a new `RandomSequence` upon exhaustion of ids. So maybe I would recommend this:

1. Make `RandomSequence` a proper `ExactSizeIterator`, so that `.next()` returns `Option<T>` instead of `T`.
2. If desired, make an `overflowing_next()` that returns `T` so the user can explicitly choose the simpler overflowing API.

**Comment by hoxxep** [comment]
PR #4 refactors `.next()` to return an `Option<T>`, and types that are small enough implement `ExactSizeIterator`. 

`u64` and `usize` on 64-bit platforms have a sequence length of `usize::MAX + 1` and therefore it's not possible to return an `ExactSizeIterator` as we would overflow the `usize`.

Let me know if you have any feedback on the change? I'll aim to release this at the same time as I rename the crate to `rand-unique`.

As a slight tangent, I had started an implementation on PR #1 to introduce `RandomSequenceConfig::with_max(max)` to generate unique sequences where all numbers are under `max`. It's a bit harder to ensure there's enough randomness in the sequences, especially for small `max <= 100`, but let me know if this is useful for you and I'll put a bit more effort into finishing that this week? The hope was that this could be used for fast slice permutations, using a sequence where `max = slice.len()`.

**Comment by JonathanWilbur** [comment]
You make a good point about `usize`. Just a thought, maybe each iterator could avoid returning `0`? By removing that one digit, you could make each an `ExactSizeIterator`,  but I'm not even sure whether the algorithm would permit this or not. I don't feel strongly about that; just an idea.

As far as PR #1 I have no use for small randoms. My use case is actually in assigning basically the equivalent of TCP port numbers, but for the OSI Transport protocol, which is not super sensitive, but is a little more secure if it is allocated out of order and they MUST be unique. They are 16-bit identifiers, just like a TCP port.

**Comment by hoxxep** [comment]
I've released `rand-unique` on `v0.2.0` with these changes. Thanks again for the suggestions.

The algorithm requires being able to XOR, and so 0 is a valid input/output value. Hopefully the current tradeoff where smaller types implement `ExactSizeIterator` is a healthy compromise -- I can see it being useful for a 256-len iterator in setting the reserve capacity of a collection, but less so for a `usize::MAX` iterator.

**Comment by hoxxep** [comment]
FYI, I've also released a fix for `size_hint` on `v0.2.1`.
